[lint]
extend-ignore = [
    "BLE001",  # Do not catch blind exception: `Exception`
    "TRY002",  # Create your own exception
    "S110",    # `try`-`except`-`pass` detected
    "S112",    # `try`-`except`-`continue` detected
    "DTZ001",  # `datetime.datetime()` called without a `tzinfo` argument
    "RUF012",  # Mutable default value for class attribute
    "RUF059",  # Unpacked variable is never used
    "B017",    # Do not assert blind exception: `Exception`
    "C401",    # Unnecessary generator (rewrite as a set comprehension)
    "PLW1510", # `subprocess.run` without explicit `check` argument
    "DTZ006",  # `datetime.datetime.fromtimestamp()` called without a `tz` argument
]
